### ISSUE TITLE
[INSTALLATION ERROR] subprocess-exited-with-error

### ISSUE THREAD

**Issue by yhy258** [JeremieMelo/pyutility#2]
Thank you for sharing the awesome package.

I tried to install the "pyutility" package through your second instruction.

```bash
git clone https://github.com/JeremieMelo/pyutility.git
cd pyutility
pip3 install --editable ..
```

However, i faced the "subprocess-exited-with-error".
The entire error is :

```
Obtaining file:///home/joon/pyutility
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/home/joon/.conda/envs/new_joon/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/joon/.conda/envs/new_joon/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/joon/.conda/envs/new_joon/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-v5gorssj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 458, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-v5gorssj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-v5gorssj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-v5gorssj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 10, in <module>
      ModuleNotFoundError: No module named 'pyutils'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.
```

In my opinion, the vital error line is "ModuleNotFoundError: No module named 'pyutils'".

**Comment by Johnny1882** [comment]
same issue

**Comment by ASU-ScopeX-Lab** [comment]
python3 setup.py install
or
python3 setup.py develop --no-deps

**Comment by Jamie810** [comment]
> python3 setup.py install or python3 setup.py develop --no-deps


when i used this method

The entire error is :
[W] Cannot import torchsummary
Traceback (most recent call last):
File "/home/suyiyang/codes/NeurOLight-main/pyutility/setup.py", line 10, in <module>
from pyutils.version import __version__
File "/home/suyiyang/codes/NeurOLight-main/pyutility/pyutils/__init__.py", line 26, in <module>
module = importlib.import_module("pyutils." + source)
File "/home/suyiyang/anaconda3/envs/test/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "/home/suyiyang/codes/NeurOLight-main/pyutility/pyutils/compute.py", line 22, in <module>
from .torch_train import set_torch_deterministic
File "/home/suyiyang/codes/NeurOLight-main/pyutility/pyutils/torch_train.py", line 51, in <module>
class DeterministicCtx:
File "/home/suyiyang/codes/NeurOLight-main/pyutility/pyutils/torch_train.py", line 52, in DeterministicCtx
def __init__(self, random_state: int | None = None) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by JeremieMelo** [comment]
> > python3 setup.py install or python3 setup.py develop --no-deps
> 
> when i used this method
> 
> The entire error is : [W] Cannot import torchsummary Traceback (most recent call last): File "/home/suyiyang/codes/NeurOLight-main/pyutility/setup.py", line 10, in from pyutils.version import **version** File "/home/suyiyang/codes/NeurOLight-main/pyutility/pyutils/**init**.py", line 26, in module = importlib.import_module("pyutils." + source) File "/home/suyiyang/anaconda3/envs/test/lib/python3.9/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/home/suyiyang/codes/NeurOLight-main/pyutility/pyutils/compute.py", line 22, in from .torch_train import set_torch_deterministic File "/home/suyiyang/codes/NeurOLight-main/pyutility/pyutils/torch_train.py", line 51, in class DeterministicCtx: File "/home/suyiyang/codes/NeurOLight-main/pyutility/pyutils/torch_train.py", line 52, in DeterministicCtx def **init**(self, random_state: int | None = None) -> None: TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'


This typing annotation is supported by python 3.10 above.

**Comment by Jamie810** [comment]
> > > python3 setup.py install or python3 setup.py develop --no-deps
> > 
> > 
> > when i used this method
> > The entire error is : [W] Cannot import torchsummary Traceback (most recent call last): File "/home/suyiyang/codes/NeurOLight-main/pyutility/setup.py", line 10, in from pyutils.version import **version** File "/home/suyiyang/codes/NeurOLight-main/pyutility/pyutils/**init**.py", line 26, in module = importlib.import_module("pyutils." + source) File "/home/suyiyang/anaconda3/envs/test/lib/python3.9/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/home/suyiyang/codes/NeurOLight-main/pyutility/pyutils/compute.py", line 22, in from .torch_train import set_torch_deterministic File "/home/suyiyang/codes/NeurOLight-main/pyutility/pyutils/torch_train.py", line 51, in class DeterministicCtx: File "/home/suyiyang/codes/NeurOLight-main/pyutility/pyutils/torch_train.py", line 52, in DeterministicCtx def **init**(self, random_state: int | None = None) -> None: TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
> 
> This typing annotation is supported by python 3.10 above.

The problem has been solved, thank you very much !
